/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcourt;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Regawa
 */
public class Toko extends javax.swing.JFrame {

    /**
     * Creates new form Toko
     */
    public Toko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JPanel();
        lToko1 = new javax.swing.JLabel();
        Gambar1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JPanel();
        lToko2 = new javax.swing.JLabel();
        Gambar2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JPanel();
        lToko3 = new javax.swing.JLabel();
        Gambar3 = new javax.swing.JLabel();
        btn4 = new javax.swing.JPanel();
        lToko4 = new javax.swing.JLabel();
        Gambar4 = new javax.swing.JLabel();
        btn5 = new javax.swing.JPanel();
        lToko5 = new javax.swing.JLabel();
        Gambar5 = new javax.swing.JLabel();
        btn6 = new javax.swing.JPanel();
        lToko6 = new javax.swing.JLabel();
        Gambar6 = new javax.swing.JLabel();
        btn7 = new javax.swing.JPanel();
        lToko7 = new javax.swing.JLabel();
        Gambar7 = new javax.swing.JLabel();
        btn8 = new javax.swing.JPanel();
        lToko8 = new javax.swing.JLabel();
        Gambar8 = new javax.swing.JLabel();
        btn9 = new javax.swing.JPanel();
        lToko9 = new javax.swing.JLabel();
        Gambar9 = new javax.swing.JLabel();
        btn10 = new javax.swing.JPanel();
        lToko10 = new javax.swing.JLabel();
        Gambar10 = new javax.swing.JLabel();
        btn11 = new javax.swing.JPanel();
        lToko11 = new javax.swing.JLabel();
        Gambar11 = new javax.swing.JLabel();
        btn12 = new javax.swing.JPanel();
        lToko12 = new javax.swing.JLabel();
        Gambar12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setBackground(new java.awt.Color(197, 197, 197));
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.setPreferredSize(new java.awt.Dimension(341, 250));
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko1.setText("jLabel1");
        btn1.add(lToko1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        btn1.add(Gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn2.setBackground(new java.awt.Color(197, 197, 197));
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.setPreferredSize(new java.awt.Dimension(341, 250));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        btn2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko2.setText("jLabel1");
        btn2.add(lToko2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        btn2.add(Gambar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        btn3.setBackground(new java.awt.Color(197, 197, 197));
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.setPreferredSize(new java.awt.Dimension(341, 250));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko3.setText("jLabel1");
        btn3.add(lToko3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        btn3.add(Gambar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, -1, -1));

        btn4.setBackground(new java.awt.Color(197, 197, 197));
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.setPreferredSize(new java.awt.Dimension(341, 250));
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        btn4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko4.setText("jLabel1");
        btn4.add(lToko4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        btn4.add(Gambar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        btn5.setBackground(new java.awt.Color(197, 197, 197));
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.setPreferredSize(new java.awt.Dimension(341, 250));
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        btn5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko5.setText("jLabel1");
        btn5.add(lToko5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        btn5.add(Gambar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btn6.setBackground(new java.awt.Color(197, 197, 197));
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.setPreferredSize(new java.awt.Dimension(341, 250));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko6.setText("jLabel1");
        btn6.add(lToko6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        btn6.add(Gambar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        btn7.setBackground(new java.awt.Color(197, 197, 197));
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.setPreferredSize(new java.awt.Dimension(341, 250));
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        btn7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko7.setText("jLabel1");
        btn7.add(lToko7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        btn7.add(Gambar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, -1, -1));

        btn8.setBackground(new java.awt.Color(197, 197, 197));
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.setPreferredSize(new java.awt.Dimension(341, 250));
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        btn8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko8.setText("jLabel1");
        btn8.add(lToko8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        btn8.add(Gambar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        btn9.setBackground(new java.awt.Color(197, 197, 197));
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.setPreferredSize(new java.awt.Dimension(341, 250));
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        btn9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko9.setText("jLabel1");
        btn9.add(lToko9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        btn9.add(Gambar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        btn10.setBackground(new java.awt.Color(197, 197, 197));
        btn10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn10.setPreferredSize(new java.awt.Dimension(341, 250));
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
        });
        btn10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko10.setText("jLabel1");
        btn10.add(lToko10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        btn10.add(Gambar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        btn11.setBackground(new java.awt.Color(197, 197, 197));
        btn11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn11.setPreferredSize(new java.awt.Dimension(341, 250));
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn11MouseClicked(evt);
            }
        });
        btn11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko11.setText("jLabel1");
        btn11.add(lToko11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));
        btn11.add(Gambar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, -1, -1));

        btn12.setBackground(new java.awt.Color(197, 197, 197));
        btn12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn12.setPreferredSize(new java.awt.Dimension(341, 250));
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn12MouseClicked(evt);
            }
        });
        btn12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lToko12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        lToko12.setText("jLabel1");
        btn12.add(lToko12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        btn12.add(Gambar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 330, 240));

        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 520, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            //method tampil nama resto here
            showNamaResto();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        String namaResto = lToko1.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        String namaResto = lToko2.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        String namaResto = lToko3.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        String namaResto = lToko4.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        String namaResto = lToko5.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        String namaResto = lToko6.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
        String namaResto = lToko7.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        String namaResto = lToko8.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        String namaResto = lToko9.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn9MouseClicked

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
        String namaResto = lToko10.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn10MouseClicked

    private void btn11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MouseClicked
        String namaResto = lToko11.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn11MouseClicked

    private void btn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseClicked
        String namaResto = lToko12.getText();
        gantiFrame(namaResto);
    }//GEN-LAST:event_btn12MouseClicked

    void gantiFrame(String namaResto) {
        //Ganti ke Frame Pemesanan
        try {
            new Pemesanan(namaResto).setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void showNamaResto() throws FileNotFoundException, IOException {
        String namaResto;
        FileInputStream fis = new FileInputStream(new File("src/data/DataMakanan12Resto.xlsx"));
        XSSFWorkbook workbook = new XSSFWorkbook(fis);
        namaResto = workbook.getSheetAt(0).getSheetName();
        lToko1.setText(namaResto);
        ImageIcon image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar1.setIcon(image);
        namaResto = workbook.getSheetAt(1).getSheetName();
        lToko2.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar2.setIcon(image);
        namaResto = workbook.getSheetAt(2).getSheetName();
        lToko3.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar3.setIcon(image);
        namaResto = workbook.getSheetAt(3).getSheetName();
        lToko4.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar4.setIcon(image);
        namaResto = workbook.getSheetAt(4).getSheetName();
        lToko5.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar5.setIcon(image);
        namaResto = workbook.getSheetAt(5).getSheetName();
        lToko6.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar6.setIcon(image);
        namaResto = workbook.getSheetAt(6).getSheetName();
        lToko7.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar7.setIcon(image);
        namaResto = workbook.getSheetAt(7).getSheetName();
        lToko8.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar8.setIcon(image);
        namaResto = workbook.getSheetAt(8).getSheetName();
        lToko9.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar9.setIcon(image);
        namaResto = workbook.getSheetAt(9).getSheetName();
        lToko10.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar10.setIcon(image);
        namaResto = workbook.getSheetAt(10).getSheetName();
        lToko11.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar11.setIcon(image);
        namaResto = workbook.getSheetAt(11).getSheetName();
        lToko12.setText(namaResto);
        image = new ImageIcon("src/img/" + namaResto + ".jpg");
        Gambar12.setIcon(image);
        fis.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar1;
    private javax.swing.JLabel Gambar10;
    private javax.swing.JLabel Gambar11;
    private javax.swing.JLabel Gambar12;
    private javax.swing.JLabel Gambar2;
    private javax.swing.JLabel Gambar3;
    private javax.swing.JLabel Gambar4;
    private javax.swing.JLabel Gambar5;
    private javax.swing.JLabel Gambar6;
    private javax.swing.JLabel Gambar7;
    private javax.swing.JLabel Gambar8;
    private javax.swing.JLabel Gambar9;
    private javax.swing.JPanel btn1;
    private javax.swing.JPanel btn10;
    private javax.swing.JPanel btn11;
    private javax.swing.JPanel btn12;
    private javax.swing.JPanel btn2;
    private javax.swing.JPanel btn3;
    private javax.swing.JPanel btn4;
    private javax.swing.JPanel btn5;
    private javax.swing.JPanel btn6;
    private javax.swing.JPanel btn7;
    private javax.swing.JPanel btn8;
    private javax.swing.JPanel btn9;
    private javax.swing.JLabel lToko1;
    private javax.swing.JLabel lToko10;
    private javax.swing.JLabel lToko11;
    private javax.swing.JLabel lToko12;
    private javax.swing.JLabel lToko2;
    private javax.swing.JLabel lToko3;
    private javax.swing.JLabel lToko4;
    private javax.swing.JLabel lToko5;
    private javax.swing.JLabel lToko6;
    private javax.swing.JLabel lToko7;
    private javax.swing.JLabel lToko8;
    private javax.swing.JLabel lToko9;
    // End of variables declaration//GEN-END:variables
}
