/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcourt;

import java.awt.Color;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Tiara Lestari
 */
public class WaitingDisplay extends javax.swing.JFrame {

    /**
     * Creates new form WaitingDisplay
     * @throws java.io.IOException
     */
    public WaitingDisplay() throws IOException {
        initComponents();
        DisplayBill();
    }
    
    private void DisplayBill() throws FileNotFoundException, IOException{
        double total = 0;
        
        XSSFRow row;
        FileInputStream fis;
        DefaultTableModel table = new DefaultTableModel();
        
        fis = new FileInputStream(new File("src//data//Book1.xlsx"));
        try (XSSFWorkbook wb = new XSSFWorkbook(fis)) {
            XSSFSheet sheet = wb.getSheetAt(0);
            
            table.addColumn("Nama");
            table.addColumn("Qty");
            table.addColumn("Harga");
            
            Iterator < Row > rowIterator = sheet.rowIterator();
            
            while(rowIterator.hasNext()){
                row = (XSSFRow) rowIterator.next();
                Iterator < Cell > cellIterator = row.cellIterator();                                        
                
                String nama;
                double qty;
                double harga;
                
                Cell cell = cellIterator.next();
                nama = cell.getStringCellValue();
                cell = cellIterator.next();
                qty = cell.getNumericCellValue();
                cell = cellIterator.next();
                harga = cell.getNumericCellValue();
                total += harga;
                
                Object[] data = new Object[]{
                    nama, qty, harga
                };
                
                table.addRow(data);
            }
            Object[] rowData = new Object[]{
                "Total", " ", total
            };
            table.addRow(rowData);
            Bill.setModel(table);
        }
    }
    
    private void SlideShow(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bill = new javax.swing.JTable();
        PrintBill = new javax.swing.JButton();
        AddMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SlideShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 26, 26));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(26, 26, 26));
        mainPanel.setMinimumSize(new java.awt.Dimension(1366, 734));
        mainPanel.setPreferredSize(new java.awt.Dimension(1366, 768));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Wait for Your Order");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 52, -1, -1));

        Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Bill);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 56, 320, 530));

        PrintBill.setBackground(new java.awt.Color(67, 1, 2));
        PrintBill.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PrintBill.setForeground(new java.awt.Color(255, 255, 255));
        PrintBill.setText("Print Bill");
        PrintBill.setPreferredSize(new java.awt.Dimension(150, 50));
        PrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBillActionPerformed(evt);
            }
        });
        mainPanel.add(PrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 620, -1, -1));

        AddMenu.setBackground(new java.awt.Color(67, 1, 2));
        AddMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AddMenu.setForeground(new java.awt.Color(255, 255, 255));
        AddMenu.setText("Add Menu");
        AddMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMenuActionPerformed(evt);
            }
        });
        mainPanel.add(AddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 620, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(SlideShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 520));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 860, 520));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBillActionPerformed
        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet sheet = wb.createSheet("Sheet 1");
        XSSFFont font = wb.createFont();
        File file = new File("src//data//Log Transaksi.xlsx");
        XSSFCellStyle cellStyle = wb.createCellStyle();
        TableModel model = Bill.getModel();
        
        for(int i = 0; i < model.getRowCount(); i++){
            XSSFRow row = sheet.createRow((short) i);
            for(int j = 0; j < model.getColumnCount(); j++){
                XSSFCell cell = row.createCell((short) j);
                cell.setCellValue(model.getValueAt(i, j).toString());
                cell.setCellStyle(cellStyle);
            }
        }
        FileOutputStream fos;
        try {
            fos = new FileOutputStream(file);
            BufferedOutputStream bos;
            bos = new BufferedOutputStream(fos);
            wb.write(bos);
            bos.close();
            fos.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WaitingDisplay.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WaitingDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintBillActionPerformed

    private void AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMenuActionPerformed
        new Toko().setVisible(true);
    }//GEN-LAST:event_AddMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaitingDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaitingDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaitingDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaitingDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new WaitingDisplay().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(WaitingDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMenu;
    private javax.swing.JTable Bill;
    private javax.swing.JButton PrintBill;
    private javax.swing.JLabel SlideShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
