/*
 * Copyright May - 2018
 * JTK POLBAN.
 * Made in Ciwaruga.
 */
package foodcourt.dashboard;

import foodcourt.security.AES;
import java.awt.Color;
import java.awt.Insets;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class tambah_pegawai extends javax.swing.JPanel {

    /**
     * Creates new form gawai
     */
    public tambah_pegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stats_pane = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        stats_pane.setBackground(new java.awt.Color(255, 153, 153));
        stats_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setMaximumSize(new java.awt.Dimension(660, 300));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcourt/images/icons8_Contacts_25px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 43));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("username");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 270, 60));
        jTextField1.setMargin(new Insets(3,13,3,3));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodcourt/images/icons8_Lock_25px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 43));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("password");
        jPasswordField1.setToolTipText("");
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 60));
        jPasswordField1.setMargin(new Insets(3,13,3,3));
        jPasswordField1.setEchoChar((char)0);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manajer Utama", "Manajer Kedua", "Manajer Ketiga" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 270, 50));

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambahkan");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 50));

        errorMsg.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(153, 0, 0));
        errorMsg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errorMsg.setText(" ");
        jPanel1.add(errorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 330, -1));

        jPanel12.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 760, 470));

        stats_pane.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 590));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setText("Tambah Pegawai");
        stats_pane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stats_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stats_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (this.jTextField1.getText().equals("username")) {
            this.jTextField1.setText("");
        }
        this.errorMsg.setText("");
        this.errorMsg.setForeground(new Color(153,0,0));
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (this.jTextField1.getText().equals("")) {
            this.jTextField1.setText("username");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        char[] input = this.jPasswordField1.getPassword();
        System.out.print(input);
        if (!input.equals("password")) {
            this.jPasswordField1.setText("");
        }
        this.jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        if (!this.jPasswordField1.getPassword().equals("")) {
            this.jPasswordField1.setText("password");
        }
        this.jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        String uname = this.jTextField1.getText();
        String pass = String.valueOf(this.jPasswordField1.getPassword());

        try {
            if (isVerified(uname, pass)) {
                tambahkanUser(uname, pass, jComboBox1.getSelectedItem().toString());
                System.out.println(pass);
            }
        } catch (IOException ex) {
            Logger.getLogger(tambah_pegawai.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(tambah_pegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tambahkanUser(String username, String password, String jabatan) throws FileNotFoundException, IOException, InterruptedException {
        int row;
        try {
            FileInputStream excelFile = new FileInputStream(new File("src/data/dataLoginManajer.xlsx"));
            Workbook workbook = new XSSFWorkbook(excelFile);
            Sheet sheet = workbook.getSheetAt(0);
            row = sheet.getLastRowNum()+1;
            Row currentRow = sheet.createRow(row);
            password = AES.kunci(password);
            
            Cell nama = currentRow.createCell(0);
            nama.setCellValue(username);
            
            Cell pass = currentRow.createCell(1);
            pass.setCellValue(password);
            
            Cell jabat = currentRow.createCell(2);
            jabat.setCellValue(jabatan);

            try {
                FileOutputStream output = new FileOutputStream(new File("src/data/dataLoginManajer.xlsx"));
                workbook.write(output);
                workbook.close();
                
                errorMsg.setForeground(new Color(51,102,0));
                errorMsg.setText("Berhasil Menambahkan!");
                this.jTextField1.setText("username");
                this.jPasswordField1.setText("password");
                
            } catch (FileNotFoundException ex) {
//                Logger.getLogger(RekeningController.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
//                Logger.getLogger(RekeningController.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
//            Logger.getLogger(RekeningController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
//            Logger.getLogger(RekeningController.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /*
        Modul pengecekan, apakah username dan password valid
     */
    private boolean isVerified(String username, String password) throws FileNotFoundException, IOException {

        //periksa username betul gak
        if (!username.contentEquals("username") && !username.contentEquals("")) //periksa password betul gak
        {
            if (!password.contentEquals("password") && !password.contentEquals("")) //periksa username udh ada belum
            {
                XSSFRow row;
                FileInputStream fis = new FileInputStream(new File("src/data/dataLoginManajer.xlsx"));
                XSSFWorkbook workbook = new XSSFWorkbook(fis);
                XSSFSheet spreadsheet = workbook.getSheetAt(0);
                Iterator< Row> rowIterator = spreadsheet.iterator();

//                row = (XSSFRow) rowIterator.next();
                while (rowIterator.hasNext()) {
                    row = (XSSFRow) rowIterator.next();
                    Iterator< Cell> cellIterator = row.cellIterator();
                    Cell cell = cellIterator.next();
                    //kalau udah ada
                    if (cell.getStringCellValue().contentEquals(username)) {
                        errorMsg.setText("username sudah ada !");
                        return false;
                    }
                }
                return true;
            } else {
                errorMsg.setText("password tidak valid !");
                return false;
            }
        } else {
            errorMsg.setText("username tidak valid !");
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMsg;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel stats_pane;
    // End of variables declaration//GEN-END:variables
}
